---@class EquipData
---@field hair integer
---@field shirt integer
---@field pants integer
---@field feet integer
---@field hand integer
---@field back integer
---@field face integer
---@field mask integer
---@field necklace integer

---@class EffectData
---@field hair integer
---@field shirt integer
---@field pants integer
---@field feet integer
---@field hand integer
---@field back integer
---@field face integer
---@field mask integer
---@field necklace integer

---@class NetAvatar
---@field posX integer
---@field posY integer
---@field netID integer
---@field name string
---@field userID integer
---@field country string
---@field punchID integer
---@field guildFlag integer
---@field isLeft boolean
---@field posXenc number
---@field posYenc number
---@field sizeX integer
---@field sizeY integer
---@field sizeXenc number
---@field sizeYenc number
---@field waterSpeed number
---@field status number
---@field irisColor Vec4
---@field pupilColor Vec4
---@field equip EquipData
---@field effect EffectData