---@class PacketRaw
---@field type integer
---@field value integer
---@field x integer
---@field y integer
---@field pX integer
---@field pY integer
---@field state integer
---@field netID integer
---@field xSpeed integer
---@field ySpeed integer