---@class PacketRaw
---@field type integer
---@field value integer
---@field x integer
---@field y integer
---@field px integer
---@field py integer
---@field state integer|nil
---@field netid integer|nil
---@field xspeed integer|nil
---@field yspeed integer|nil