---@class TankPacket
---@field secnetid integer
---@field padding1 integer
---@field padding2 integer
---@field padding3 integer
---@field padding4 integer
---@field padding5 integer
---@field time integer